CREATE OR REPLACE FUNCTION TAZ_CREDITOCLIENTE(
CODC IN PCCLIENT.CODCLI%TYPE,
LIM IN NUMBER
 )
RETURN VARCHAR2 IS
LIMCLI NUMBER;
BEGIN
SELECT LIMCRED INTO LIMCLI FROM PCCLIENT WHERE CODCLI = CODC;
IF (LIM < LIMCLI) THEN
RETURN 'APROVADO';
ELSE
RETURN 'NEGADO';
END IF;
END;
