CREATE OR REPLACE TRIGGER TAZ_TRG_CONTRIBUINTE
 BEFORE 
 INSERT OR UPDATE OF CONTRIBUINTE, CONSUMIDORFINAL, IEENT
 ON PCCLIENT
 REFERENCING OLD AS OLD NEW AS NEW
 FOR EACH ROW 
BEGIN
/* TRIGGER AJUSTAR CADASTRO DO CLIENTE NA 302
   TAIRONE MORAIS - ANALISTA DE SISTEMAS - AÇO POTIGUAR - 16/08/2017 */
    /* VERIFICA SE O CAMPO INSCRIÇÃO ESTADUAL FOR ALTERADO PARA ISENTO MUDA OS CAMPOS
       CONTRIBUINTE PARA NÃO E CONSUMIDOR PARA SIM SE NÃO O INVERSO        */
 /* 11/01/2019 ACRESCENTADO PRA VALIDAR CASO A PESSOA DIGITE ISENTA ALTERAR PARA ISENTO */
    IF(:NEW.IEENT LIKE '%ISENTA%') THEN
            :NEW.IEENT := 'ISENTO';
    END IF;
    IF(:NEW.IEENT LIKE '%ISENTO%') THEN
            :NEW.CONTRIBUINTE := 'N';
            :NEW.CONSUMIDORFINAL := 'S';
            ELSE
            :NEW.CONTRIBUINTE := 'S';
            :NEW.CONSUMIDORFINAL := 'N';
    END IF;
END;
