--select verificar as jobs que criei
SELECT 
OWNER, JOB_NAME, JOB_TYPE, JOB_ACTION, PROGRAM_NAME, JOB_STYLE, comments, JOB_CREATOR, STATE, ENABLED, REPEAT_INTERVAL, LAST_RUN_DURATION
, LOGGING_LEVEL, SYSTEM, RUN_COUNT
--,START_DATE, LAST_START_DATE, LAST_RUN_DURATION, NEXT_RUN_DATE
FROM ALL_SCHEDULER_JOBS
where job_name like '%TAZ%';

SELECT 
OWNER, JOB_NAME, JOB_TYPE, JOB_ACTION, comments, STATE 

FROM DBA_SCHEDULER_JOBS;

disabilitar jobs
--exec dbms_scheduler.disable(‘GATHER_STATS_JOB’)
