SELECT
P.CODPROD, D.DESCRICAO, 
ROUND ( SUM(P.QT) * SUM(P.PVENDA) ,2 ) VLVENDAS
, ROUND ( RATIO_TO_REPORT( (SUM(P.QT) * SUM(P.PVENDA)) ) OVER() * 100 , 2 ) AS "%"

FROM PCPEDI P, PCPEDC E, PCPRODUT D
WHERE P.CODCLI = E.CODCLI
AND P.NUMPED = E.NUMPED
AND P.CODPROD = D.CODPROD 
AND P.DATA BETWEEN TO_DATE('01/01/2021', 'DD/MM/YYYY') AND TO_DATE('30/06/2021', 'DD/MM/YYYY')
AND E.CONDVENDA IN (1, 7)
AND P.POSICAO = 'F'
GROUP BY P.CODPROD, D.DESCRICAO
ORDER BY ROUND ( RATIO_TO_REPORT( (SUM(P.QT) * SUM(P.PVENDA)) ) OVER() * 100 , 2 ) DESC

