SELECT
P.VERSAOAPLICATIVO, P.ESTACAO, P.USUARIOREDE, P.NOMEOBJETO, P.ACAO, P.MATRICULAUSUARIO, P.NOMEAPLICACAO, P.DATALOG
, DBMS_LOB.SUBSTR( P.VALOROLD, 4000, 1 ) VLANT, DBMS_LOB.SUBSTR( P.VALORNEW, 4000, 1 ) VLATUAL
FROM PCLOGCADASTRO P
WHERE P.NOMEOBJETO = 'PCCLIENT'
AND P.DATALOG >= SYSDATE-30
