SELECT
P.NUMVIASMAPASEP, P.CONDVENDA, P.POSICAO, P.ORIGEMPED, P.NUMPEDENTFUT, P.NUMPED, P.CODCLI, P.VLTOTAL, P.CODUSUR, P.DATA, P.OBSFRETENF3
FROM PCPEDC P
WHERE NVL(P.NUMVIASMAPASEP, 0) = 0
AND P.DATA >= TRUNC(SYSDATE-180)
AND P.POSICAO NOT IN ('C', 'F', 'B')
AND P.ORIGEMPED = 'T'
AND (((NVL(P.VENDAASSISTIDA, 'N') = 'S') AND (P.CONDVENDA = 8) AND 
            ((SELECT PC.POSICAO 
                  FROM PCPEDC PC 
                 WHERE PC.CONDVENDA = 7 
                   AND NVL(PC.VENDAASSISTIDA, 'N') = 'S' 
                   AND PC.NUMPED = P.NUMPEDENTFUT) = 'F')) OR 
            (NVL(P.VENDAASSISTIDA, 'N') = 'N'))


